import type { FinanceProduct } from "@/types/finance";

export const FINANCE_PRODUCTS: FinanceProduct[] = [
  {
    id: "bangkok-bank-poonphol-green-pea",
    name: "Bangkok Bank Poonphol Green Solar",
    type: "loan",
    enabledByDefault: false,
    annualRatePercent: 6.5,
    termMonths: 60,
    loanToValueRatio: 1,
    notes: "Residential solar financing benchmark. Modeled as up to 100% of project price, but approval depends on collateral value, credit review, fees, and floating rates. Uses Bangkok Bank PEA page MRR assumption as of 26 Feb 2026: 6.50% p.a.",
  },
  {
    id: "krungsri-sme-solar-rooftop",
    name: "Krungsri SME Solar Rooftop",
    type: "loan",
    enabledByDefault: false,
    annualRatePercent: 3.5,
    termMonths: 84,
    loanToValueRatio: 1,
    notes: "Business-only reference: Krungsri SME Solar Rooftop advertises a special fixed rate from 3.5% p.a. for the first 2 years and maximum tenor up to 7 years. Do not use for normal residential customers unless they qualify as SME.",
  },
  {
    id: "comsys-0-percent-6m",
    name: "Comsys 0% 6 Months",
    type: "installment",
    enabledByDefault: false,
    annualRatePercent: 0,
    termMonths: 6,
    notes: "Short-term instalment benchmark for low-friction sales closes.",
  },
  {
    id: "saimai-10m-installment",
    name: "Saimai 10-Month Installment",
    type: "installment",
    enabledByDefault: false,
    annualRatePercent: 10,
    termMonths: 10,
    notes: "Reference instalment plan based on competitor field offers.",
  },
  {
    id: "personal-income-tax-deduction",
    name: "Thailand Solar Rooftop Tax Deduction",
    type: "tax_credit",
    enabledByDefault: true,
    maxSubsidyTHB: 200000,
    taxBenefitRatePercent: 20,
    notes: "Royal Decree No. 805 / 2026: modelled as a one-time personal income tax deduction for qualifying on-grid residential solar expenses from 3 Mar 2026 to 31 Dec 2028, capped at THB 200,000. The calculator estimates cash benefit at 20% of the eligible deduction; actual tax benefit depends on taxpayer income and documentation.",
  },
  {
    id: "unconfirmed-direct-subsidy-placeholder",
    name: "Direct Subsidy Placeholder",
    type: "subsidy",
    enabledByDefault: false,
    subsidyTHB: 0,
    maxSubsidyTHB: 0,
    notes: "Disabled until KSolar confirms an active direct-cash household subsidy. Net billing is handled through the export tariff input, not as a capex subsidy.",
  },
];
