/**
 * Inverter catalog for KSolar.
 *
 * Two segments:
 *   "ksolar-bom"  — residential 3–20 kW inverters used in KSolar BOM quotes.
 *                   Prices come from bom-catalog.ts market estimates (THB).
 *                   Technical specs are representative datasheets values.
 *   "isolar-bp"   — commercial 30–320 kW inverters scraped from iSolarBP
 *                   设计物料管理 > 逆变器 (2026-04-20). Prices in CNY → THB.
 *
 * Manufacturer note: all iSolarBP inverters are Sungrow (阳光电源).
 * KSolar-BOM residential inverters use the Growatt SUN-K series.
 */
import { cnyToThb } from "@/lib/config/currency";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type InverterPhase = "1P" | "3P";
export type InverterMode = "ongrid" | "hybrid";
export type InverterSource = "ksolar-bom" | "isolar-bp";

export interface InverterSpec {
  /** Unique kebab-case slug */
  id: string;
  /** Data origin */
  source: InverterSource;
  manufacturer: string;
  model: string;
  /** Grid phase */
  phase: InverterPhase;
  /** ongrid = grid-tie only; hybrid = supports battery */
  mode: InverterMode;
  /** Rated AC output power (kW) */
  ratedPowerKW: number;
  /** CNY price from iSolarBP; null = not listed or not applicable */
  priceCNY: number | null;
  /** THB price; null = not listed */
  unitCostTHB: number | null;
  // --- DC input ---
  maxInputVoltageV: number;
  mpptVoltageMinV: number;
  mpptVoltageMaxV: number;
  mpptCount: number;
  maxStringCount: number;
  maxInputCurrentA: number;
  // --- AC output ---
  maxOutputCurrentA: number;
  /** Rated grid voltage (V) — 230 for 1P, 400 for 3P */
  ratedGridVoltageV: number;
  // --- Physical ---
  /** Max DC input cable cross-section (mm²) */
  maxCableMM2: number | null;
  dimWidthMm: number | null;
  dimDepthMm: number | null;
  dimHeightMm: number | null;
  weightKg: number | null;
}

// ---------------------------------------------------------------------------
// Segment A — KSolar BOM residential inverters (3–20 kW)
// Prices: THB market estimates as of 2026-04 (no CNY source).
// Specs: representative datasheet values for Growatt SUN-K series.
// ---------------------------------------------------------------------------

const KSOLAR_RESIDENTIAL: InverterSpec[] = [
  // ── 1-Phase On-Grid ──────────────────────────────────────────────────────
  {
    id: "growatt-sun-3k-g04p1-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-3K-G04P1-EU-AM1",
    phase: "1P",
    mode: "ongrid",
    ratedPowerKW: 3,
    priceCNY: null,
    unitCostTHB: 8400,
    maxInputVoltageV: 600,
    mpptVoltageMinV: 60,
    mpptVoltageMaxV: 550,
    mpptCount: 1,
    maxStringCount: 2,
    maxInputCurrentA: 12.5,
    maxOutputCurrentA: 13.6,
    ratedGridVoltageV: 230,
    maxCableMM2: 6,
    dimWidthMm: 350,
    dimDepthMm: 130,
    dimHeightMm: 480,
    weightKg: 11,
  },
  {
    id: "growatt-sun-5k-g05p1-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-5K-G05P1-EU-AM2",
    phase: "1P",
    mode: "ongrid",
    ratedPowerKW: 5,
    priceCNY: null,
    unitCostTHB: 12100,
    maxInputVoltageV: 600,
    mpptVoltageMinV: 70,
    mpptVoltageMaxV: 550,
    mpptCount: 1,
    maxStringCount: 2,
    maxInputCurrentA: 12.5,
    maxOutputCurrentA: 21.7,
    ratedGridVoltageV: 230,
    maxCableMM2: 6,
    dimWidthMm: 350,
    dimDepthMm: 130,
    dimHeightMm: 480,
    weightKg: 13,
  },
  {
    id: "growatt-sun-10k-g02p1-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-10K-G02P1-EU-AM2",
    phase: "1P",
    mode: "ongrid",
    ratedPowerKW: 10,
    priceCNY: null,
    unitCostTHB: 19800,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 100,
    mpptVoltageMaxV: 950,
    mpptCount: 2,
    maxStringCount: 4,
    maxInputCurrentA: 25,
    maxOutputCurrentA: 43.5,
    ratedGridVoltageV: 230,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 20,
  },
  // ── 1-Phase Hybrid ───────────────────────────────────────────────────────
  {
    id: "growatt-sun-5k-sg04lp1-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-5K-SG04LP1-EU-SM2",
    phase: "1P",
    mode: "hybrid",
    ratedPowerKW: 5,
    priceCNY: null,
    unitCostTHB: 23500,
    maxInputVoltageV: 600,
    mpptVoltageMinV: 70,
    mpptVoltageMaxV: 550,
    mpptCount: 2,
    maxStringCount: 4,
    maxInputCurrentA: 25,
    maxOutputCurrentA: 21.7,
    ratedGridVoltageV: 230,
    maxCableMM2: 6,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 21,
  },
  {
    id: "growatt-sun-10k-sg05lp1-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-10K-SG05LP1-EU",
    phase: "1P",
    mode: "hybrid",
    ratedPowerKW: 10,
    priceCNY: null,
    unitCostTHB: 46700,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 100,
    mpptVoltageMaxV: 950,
    mpptCount: 2,
    maxStringCount: 4,
    maxInputCurrentA: 25,
    maxOutputCurrentA: 43.5,
    ratedGridVoltageV: 230,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 23,
  },
  // ── 3-Phase On-Grid ──────────────────────────────────────────────────────
  {
    id: "growatt-sun-6k-g06p3-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-6K-G06P3-EU-BM2-P1",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 6,
    priceCNY: null,
    unitCostTHB: 16300,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 850,
    mpptCount: 2,
    maxStringCount: 4,
    maxInputCurrentA: 26,
    maxOutputCurrentA: 9.1,
    ratedGridVoltageV: 400,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 19,
  },
  {
    id: "growatt-sun-10k-g06p3-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-10K-G06P3-EU-BM2-P1",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 10,
    priceCNY: null,
    unitCostTHB: 17800,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 850,
    mpptCount: 2,
    maxStringCount: 4,
    maxInputCurrentA: 26,
    maxOutputCurrentA: 15.2,
    ratedGridVoltageV: 400,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 20,
  },
  {
    id: "growatt-sun-15k-g06p3-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-15K-G06P3-EU-BM2-P1",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 15,
    priceCNY: null,
    unitCostTHB: 24300,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 850,
    mpptCount: 3,
    maxStringCount: 6,
    maxInputCurrentA: 40,
    maxOutputCurrentA: 22.8,
    ratedGridVoltageV: 400,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 23,
  },
  {
    id: "growatt-sun-20k-g05",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-20K-G05",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 20,
    priceCNY: null,
    unitCostTHB: 27500,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 200,
    mpptVoltageMaxV: 850,
    mpptCount: 4,
    maxStringCount: 8,
    maxInputCurrentA: 50,
    maxOutputCurrentA: 30.4,
    ratedGridVoltageV: 400,
    maxCableMM2: 16,
    dimWidthMm: 460,
    dimDepthMm: 200,
    dimHeightMm: 650,
    weightKg: 30,
  },
  // ── 3-Phase Hybrid ───────────────────────────────────────────────────────
  {
    id: "growatt-sun-5k-sg05lp3-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-5K-SG05LP3-EU-SM2",
    phase: "3P",
    mode: "hybrid",
    ratedPowerKW: 5,
    priceCNY: null,
    unitCostTHB: 45800,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 850,
    mpptCount: 2,
    maxStringCount: 4,
    maxInputCurrentA: 26,
    maxOutputCurrentA: 7.6,
    ratedGridVoltageV: 400,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 23,
  },
  {
    id: "growatt-sun-10k-sg04lp3-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-10K-SG04LP3-EU",
    phase: "3P",
    mode: "hybrid",
    ratedPowerKW: 10,
    priceCNY: null,
    unitCostTHB: 56500,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 850,
    mpptCount: 2,
    maxStringCount: 4,
    maxInputCurrentA: 26,
    maxOutputCurrentA: 15.2,
    ratedGridVoltageV: 400,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 25,
  },
  {
    id: "growatt-sun-15k-sg05lp3-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-15K-SG05LP3-EU-SM2",
    phase: "3P",
    mode: "hybrid",
    ratedPowerKW: 15,
    priceCNY: null,
    unitCostTHB: 62800,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 850,
    mpptCount: 3,
    maxStringCount: 6,
    maxInputCurrentA: 40,
    maxOutputCurrentA: 22.8,
    ratedGridVoltageV: 400,
    maxCableMM2: 10,
    dimWidthMm: 395,
    dimDepthMm: 175,
    dimHeightMm: 590,
    weightKg: 28,
  },
  {
    id: "growatt-sun-20k-sg05lp3-eu",
    source: "ksolar-bom",
    manufacturer: "Growatt",
    model: "SUN-20K-SG05LP3-EU-SM2",
    phase: "3P",
    mode: "hybrid",
    ratedPowerKW: 20,
    priceCNY: null,
    unitCostTHB: 84000,
    maxInputVoltageV: 1000,
    mpptVoltageMinV: 200,
    mpptVoltageMaxV: 850,
    mpptCount: 4,
    maxStringCount: 8,
    maxInputCurrentA: 50,
    maxOutputCurrentA: 30.4,
    ratedGridVoltageV: 400,
    maxCableMM2: 16,
    dimWidthMm: 460,
    dimDepthMm: 200,
    dimHeightMm: 650,
    weightKg: 35,
  },
];

// ---------------------------------------------------------------------------
// Segment B — iSolarBP commercial inverters (30–320 kW)
// All Sungrow (阳光电源). Scraped 2026-04-20.
// Prices in CNY → converted to THB; null = not listed in iSolarBP.
// ---------------------------------------------------------------------------

const ISOLAR_COMMERCIAL: InverterSpec[] = [
  // iSolarBP commercial: 40kW
  {
    id: "sungrow-sg40cx-p3-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG40CX-P3-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 40,
    priceCNY: null,
    unitCostTHB: null,
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 4,
    maxStringCount: 7,
    maxInputCurrentA: 132,
    maxOutputCurrentA: 66.9,
    ratedGridVoltageV: 400,
    maxCableMM2: 35,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 40,
  },
  // iSolarBP commercial: 30kW
  {
    id: "sungrow-sg30t-p2-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG30T-P2-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 30,
    priceCNY: null,
    unitCostTHB: null,
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 3,
    maxStringCount: 5,
    maxInputCurrentA: 100,
    maxOutputCurrentA: 50,
    ratedGridVoltageV: 400,
    maxCableMM2: 25,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 25,
  },
  // iSolarBP commercial: 50kW
  {
    id: "sungrow-sg50cx-p3-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG50CX-P3-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 50,
    priceCNY: 4820,
    unitCostTHB: cnyToThb(4820),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 4,
    maxStringCount: 8,
    maxInputCurrentA: 160,
    maxOutputCurrentA: 83.6,
    ratedGridVoltageV: 400,
    maxCableMM2: 50,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 40,
  },
  // iSolarBP commercial: 100kW
  {
    id: "sungrow-sg100cx",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG100CX",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 100,
    priceCNY: null,
    unitCostTHB: null,
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 200,
    mpptVoltageMaxV: 1000,
    mpptCount: 9,
    maxStringCount: 18,
    maxInputCurrentA: 234,
    maxOutputCurrentA: 158.8,
    ratedGridVoltageV: 400,
    maxCableMM2: 240,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 89,
  },
  // iSolarBP commercial: 250kW
  {
    id: "sungrow-sg250hx-20-6",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG250HX-20（6路）",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 250,
    priceCNY: 27000,
    unitCostTHB: cnyToThb(27000),
    maxInputVoltageV: 1500,
    mpptVoltageMinV: 500,
    mpptVoltageMaxV: 1500,
    mpptCount: 6,
    maxStringCount: 24,
    maxInputCurrentA: 390,
    maxOutputCurrentA: 198.5,
    ratedGridVoltageV: 800,
    maxCableMM2: 400,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 106,
  },
  // iSolarBP commercial: 320kW (6路)
  {
    id: "sungrow-sg320hx-6",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG320HX（6路）",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 320,
    priceCNY: 29636,
    unitCostTHB: cnyToThb(29636),
    maxInputVoltageV: 1500,
    mpptVoltageMinV: 500,
    mpptVoltageMaxV: 1500,
    mpptCount: 6,
    maxStringCount: 30,
    maxInputCurrentA: 450,
    maxOutputCurrentA: 254,
    ratedGridVoltageV: 800,
    maxCableMM2: 400,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 106,
  },
  // iSolarBP commercial: 30kW
  {
    id: "sungrow-sg30cx-p2-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG30CX-P2-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 30,
    priceCNY: 3000,
    unitCostTHB: cnyToThb(3000),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 3,
    maxStringCount: 6,
    maxInputCurrentA: 90,
    maxOutputCurrentA: 50.2,
    ratedGridVoltageV: 400,
    maxCableMM2: 35,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 30,
  },
  // iSolarBP commercial: 40kW
  {
    id: "sungrow-sg40cx-p2-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG40CX-P2-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 40,
    priceCNY: 4325,
    unitCostTHB: cnyToThb(4325),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 3,
    maxStringCount: 6,
    maxInputCurrentA: 90,
    maxOutputCurrentA: 66.9,
    ratedGridVoltageV: 400,
    maxCableMM2: 35,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 35,
  },
  // iSolarBP commercial: 33kW
  {
    id: "sungrow-sg33cx-p2-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG33CX-P2-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 33,
    priceCNY: 3189,
    unitCostTHB: cnyToThb(3189),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 3,
    maxStringCount: 6,
    maxInputCurrentA: 90,
    maxOutputCurrentA: 55.2,
    ratedGridVoltageV: 400,
    maxCableMM2: 35,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 35,
  },
  // iSolarBP commercial: 50kW
  {
    id: "sungrow-sg50cx-p2-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG50CX-P2-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 50,
    priceCNY: 4780,
    unitCostTHB: cnyToThb(4780),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 4,
    maxStringCount: 8,
    maxInputCurrentA: 120,
    maxOutputCurrentA: 83,
    ratedGridVoltageV: 400,
    maxCableMM2: 50,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 38,
  },
  // iSolarBP commercial: 50kW (P2H)
  {
    id: "sungrow-sg50cx-p2h-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG50CX-P2H-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 50,
    priceCNY: 5032,
    unitCostTHB: cnyToThb(5032),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 160,
    mpptVoltageMaxV: 1000,
    mpptCount: 4,
    maxStringCount: 5,
    maxInputCurrentA: 100,
    maxOutputCurrentA: 83.6,
    ratedGridVoltageV: 400,
    maxCableMM2: 50,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 38,
  },
  // iSolarBP commercial: 320kW (12路)
  {
    id: "sungrow-sg320hx-12",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG320HX（12路）",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 320,
    priceCNY: 29636,
    unitCostTHB: cnyToThb(29636),
    maxInputVoltageV: 1500,
    mpptVoltageMinV: 500,
    mpptVoltageMaxV: 1500,
    mpptCount: 12,
    maxStringCount: 24,
    maxInputCurrentA: 480,
    maxOutputCurrentA: 254,
    ratedGridVoltageV: 800,
    maxCableMM2: 400,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 116,
  },
  // iSolarBP commercial: 150kW
  {
    id: "sungrow-sg150cx-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG150CX-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 150,
    priceCNY: 21000,
    unitCostTHB: cnyToThb(21000),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 180,
    mpptVoltageMaxV: 1000,
    mpptCount: 7,
    maxStringCount: 21,
    maxInputCurrentA: 336,
    maxOutputCurrentA: 250.7,
    ratedGridVoltageV: 400,
    maxCableMM2: 300,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 96,
  },
  // iSolarBP commercial: 110kW (P2H)
  {
    id: "sungrow-sg110cx-p2h-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG110CX-P2H-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 110,
    priceCNY: 15400,
    unitCostTHB: cnyToThb(15400),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 180,
    mpptVoltageMaxV: 1000,
    mpptCount: 9,
    maxStringCount: 11,
    maxInputCurrentA: 220,
    maxOutputCurrentA: 183.3,
    ratedGridVoltageV: 400,
    maxCableMM2: 240,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 82,
  },
  // iSolarBP commercial: 320kW (16路)
  {
    id: "sungrow-sg320hx-16",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG320HX（16路）",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 320,
    priceCNY: 29636,
    unitCostTHB: cnyToThb(29636),
    maxInputVoltageV: 1500,
    mpptVoltageMinV: 500,
    mpptVoltageMaxV: 1500,
    mpptCount: 16,
    maxStringCount: 32,
    maxInputCurrentA: 480,
    maxOutputCurrentA: 254,
    ratedGridVoltageV: 800,
    maxCableMM2: 400,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 116,
  },
  // iSolarBP commercial: 320kW (14路)
  {
    id: "sungrow-sg320hx-14",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG320HX（14路）",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 320,
    priceCNY: 29636,
    unitCostTHB: cnyToThb(29636),
    maxInputVoltageV: 1500,
    mpptVoltageMinV: 500,
    mpptVoltageMaxV: 1500,
    mpptCount: 14,
    maxStringCount: 28,
    maxInputCurrentA: 420,
    maxOutputCurrentA: 254,
    ratedGridVoltageV: 800,
    maxCableMM2: 400,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 116,
  },
  // iSolarBP commercial: 225kW
  {
    id: "sungrow-sg225hx",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG225HX",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 225,
    priceCNY: 25000,
    unitCostTHB: cnyToThb(25000),
    maxInputVoltageV: 1500,
    mpptVoltageMinV: 500,
    mpptVoltageMaxV: 1500,
    mpptCount: 12,
    maxStringCount: 24,
    maxInputCurrentA: 360,
    maxOutputCurrentA: 178,
    ratedGridVoltageV: 800,
    maxCableMM2: 300,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 99,
  },
  // iSolarBP commercial: 110kW (HX)
  {
    id: "sungrow-sg110hx-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG110HX-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 110,
    priceCNY: 15400,
    unitCostTHB: cnyToThb(15400),
    maxInputVoltageV: 1500,
    mpptVoltageMinV: 500,
    mpptVoltageMaxV: 1500,
    mpptCount: 6,
    maxStringCount: 12,
    maxInputCurrentA: 180,
    maxOutputCurrentA: 87,
    ratedGridVoltageV: 800,
    maxCableMM2: 150,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 75,
  },
  // iSolarBP commercial: 110kW (P2)
  {
    id: "sungrow-sg110cx-p2-cn",
    source: "isolar-bp",
    manufacturer: "Sungrow",
    model: "SG110CX-P2-CN",
    phase: "3P",
    mode: "ongrid",
    ratedPowerKW: 110,
    priceCNY: 15400,
    unitCostTHB: cnyToThb(15400),
    maxInputVoltageV: 1100,
    mpptVoltageMinV: 180,
    mpptVoltageMaxV: 1000,
    mpptCount: 9,
    maxStringCount: 18,
    maxInputCurrentA: 270,
    maxOutputCurrentA: 183,
    ratedGridVoltageV: 400,
    maxCableMM2: 240,
    dimWidthMm: 1800,
    dimDepthMm: 1300,
    dimHeightMm: 1800,
    weightKg: 82,
  },
];

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

/** All inverters: residential BOM units first, then iSolarBP commercial */
export const INVERTER_CATALOG: InverterSpec[] = [
  ...KSOLAR_RESIDENTIAL,
  ...ISOLAR_COMMERCIAL,
];

/** Only the 13 residential inverters used in KSolar BOM quotes */
export const RESIDENTIAL_INVERTERS: InverterSpec[] = KSOLAR_RESIDENTIAL;

/** Only the 19 iSolarBP commercial inverters */
export const COMMERCIAL_INVERTERS: InverterSpec[] = ISOLAR_COMMERCIAL;

/** Convenience: look up an inverter by id */
export function findInverter(id: string): InverterSpec | undefined {
  return INVERTER_CATALOG.find((inv) => inv.id === id);
}

/**
 * Filter residential inverters for a specific topology.
 * @example filterResidentialInverters("1P", "ongrid") // → 3 on-grid 1P units
 */
export function filterResidentialInverters(
  phase: InverterPhase,
  mode: InverterMode
): InverterSpec[] {
  return KSOLAR_RESIDENTIAL.filter(
    (inv) => inv.phase === phase && inv.mode === mode
  );
}
